## ---------------------------------------------------------------------------------
## Build environment image
FROM ubuntu:19.10 AS base

MAINTAINER Oliver Fuhrer, oliverf@vulcan.com

ENV ESMF_BRANCH=ESMF_8_0_0 \
    NCEP_SHA=3da51e139d5cd731c9fc27f39d88cb4e1328212b \
    FMS_SHA=f68878549364e39591216874d5a922c06b7d3a91 \
    STOCHASTIC_SHA=01739da377d603c9c8d6d666afe2442260fd79d1 \
    FV3ATM_SHA=b48b640f4d8cae978e2d98e149412054d74dcce7 \
    FV3CONFIG_BRANCH=v0.3.2

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gcc \
    git \
    libblas-dev \
    liblapack-dev \
    libnetcdf-dev \
    libnetcdff-dev \
    perl \
    make \
    rsync \
    libffi-dev \
    openssl \
    libopenmpi3 \
    python3 \
    python3-pip \
    bats

RUN ln -s /bin/python3 /bin/python && \
    ln -s /bin/pip3 /bin/pip && \
    pip install --no-cache-dir pyyaml

RUN git config --global user.email "you@example.com" && \
    git config --global user.name "Your Name"

## ---------------------------------------------------------------------------------
## Build NCEPlibs
RUN git config --global http.sslverify false && \
    git clone https://github.com/NCAR/NCEPlibs.git /NCEPlibs && \
    mkdir /opt/NCEPlibs && \
    cd NCEPlibs && \
    git checkout $NCEP_SHA && \
    echo "y" | ./make_ncep_libs.sh -s linux -c gnu -d /opt/NCEPlibs -o 1 && \
    /bin/rm -rf /NCEPlibs && mv /opt/NCEPlibs /NCEPlibs

## ---------------------------------------------------------------------------------
## Build ESMF
ENV ESMF_DIR=/esmf \
    ESMF_INSTALL_PREFIX=/usr/local/esmf \
    ESMF_NETCDF_INCLUDE=/usr/include \
    ESMF_NETCDF_LIBS="-lnetcdf -lnetcdff" \
    ESMF_BOPT=O3
RUN git clone -b $ESMF_BRANCH --depth 1 https://git.code.sf.net/p/esmf/esmf $ESMF_DIR && \
    cd $ESMF_DIR && \
    make lib -j8 && \
    make install && \
    make installcheck

## ---------------------------------------------------------------------------------
## Build FMS
COPY patches/PATCH-FMS-affinity.c-fix-getpid.patch /
COPY patches/PATCH-FMS-libFMS_Makefile.am-add-sat-vapor-pres.patch /
RUN git clone https://github.com/NOAA-GFDL/FMS.git /FMS && \
    cd /FMS && git checkout $FMS_SHA && \
    git am /PATCH-FMS-affinity.c-fix-getpid.patch && \
    git am /PATCH-FMS-libFMS_Makefile.am-add-sat-vapor-pres.patch && \
    CC=mpicc FC=mpifort LDFLAGS="-L/usr/lib" LOG_DRIVER_FLAGS="--comments" \
      CPPFLAGS="-I/usr/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500 -DGFS_PHYS" \
      FCFLAGS="-fcray-pointer -Waliasing -ffree-line-length-none -fno-range-check -fdefault-real-8 -fdefault-double-8 -fopenmp" \
      autoreconf --install && \
    CC=mpicc FC=mpifort LDFLAGS="-L/usr/lib" LOG_DRIVER_FLAGS="--comments" \
      CPPFLAGS="-I/usr/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500 -DGFS_PHYS" \
      FCFLAGS="-fcray-pointer -Waliasing -ffree-line-length-none -fno-range-check -fdefault-real-8 -fdefault-double-8 -fopenmp" \
      ./configure && \
    CC=mpicc FC=mpifort LDFLAGS="-L/usr/lib" LOG_DRIVER_FLAGS="--comments" \
      CPPFLAGS="-I/usr/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500 -DGFS_PHYS" \
      FCFLAGS="-fcray-pointer -Waliasing -ffree-line-length-none -fno-range-check -fdefault-real-8 -fdefault-double-8 -fopenmp" \
      make -j8 && \
    mv /FMS/*/*.mod /FMS/*/*.o /FMS/*/*.h /FMS/

## ---------------------------------------------------------------------------------
## Build fv3atm executable

ENV NCEP_DIR=/NCEPlibs \
    FMS_DIR=/FMS \
    ESMF_DIR=/usr/local/esmf

ENV ESMF_INC="-I/usr/local/esmf/include -I${ESMF_DIR}/mod/modO3/Linux.gfortran.64.mpiuni.default/" \
    LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ESMF_DIR}/lib/libO3/Linux.gfortran.64.mpiuni.default/:${FMS_DIR}/libFMS/.libs/

COPY patches/PATCH-stochastic_physics-update_ca.F90-fix-logical-comparisons.patch /
RUN git clone https://github.com/noaa-psd/stochastic_physics.git /stochastic_physics && \
    cd /stochastic_physics && git checkout $STOCHASTIC_SHA

COPY patches/PATCH-fv3atm-apply-fixes.patch /
RUN git clone https://github.com/NOAA-EMC/fv3atm.git /FV3 && \
    cd /FV3 && git checkout $FV3ATM_SHA && \
    git submodule update --init && \
    git am /PATCH-fv3atm-apply-fixes.patch && \
    mkdir namphysics && mkdir conf

RUN /bin/rm -f /PATCH-*
COPY etc/make.rules /FV3/conf/make.rules
COPY etc/configure.fv3.gnu_docker /FV3/conf/configure.fv3

# compile base (should speedup compilation of injected code)
#RUN cd /FV3 && make clean && make libs -j8
#RUN cd /FV3/atmos_cubed_sphere && make clean && cd /FV3 && make -j8

## ## ---------------------------------------------------------------------------------
## ## Install fv3config
## RUN git clone -b $FV3CONFIG_BRANCH https://github.com/VulcanClimateModeling/fv3config.git && \
##     cd fv3config && \
##     pip install --no-cache-dir -e . && \
##     python -m fv3config.download_data

## ---------------------------------------------------------------------------------
## Not meant for entering
CMD ["bash"]
